use_frameworks!
platform :ios, '12.0'

target 'PinballMap' do

pod 'ReSwift', '4.1.1'
pod 'HottPotato', :git => 'https://github.com/hkellaway/HottPotato.git', :tag => '0.1.0'
pod 'TinyConstraints', '4.0.0'

end

